export const users = [
  {
    username: "saman",
    password: "123",
    email: "samans76@gmail.com",
    userTier: "admin",
  },
  {
    username: "sara",
    password: "sara1",
    email: "sara@gmail.com",
    userTier: "normal",
  },
];

export const postsList = [
  {
    postName: "overlord",
    score: "8.2",
    genreList: ["اکشن", "ماجراجویی", "فانتزی", "جادویی"],
    country: "ژاپن",
    startYear: "2012",
    endYear: "",
    isOnGoing: true,
    language: "ٰژاپنی",
    duration: "24",
    summery:
      "یک مرد جوان به عنوان یک پادشاه جنگجو در یک بازی ویدئویی به دام می افتد و تصمیم می گیرد که این دنیای جدید را امپراتوری خود کند.",
    seasonNumber: "4",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/overlord.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Overlord/Overlord.IV/Overlord.IV.01.720p.Bia2Anime.mkv",
  },
  {
    postName: "Boruto",
    score: "6.7",
    genreList: ["اکشن", "ماجراجویی", "فانتزی", "شونن", "مدرسه ای", "جادویی"],
    country: "ژاپن",
    startYear: "2018",
    endYear: "",
    isOnGoing: true,
    language: "ژاپنی",
    duration: "24",
    summery:
      "ناروتو یک نینجای جوان بود که به رویای خود یعنی تبدیل شدن به قویترین و برترین نینجای دهکده خود رسید و سرانجام چهره‌ی صورت او را به عنوان هوکاگه در کنار دیگر هوکاگه ها قرار دادند. اما داستان انیمه Boruto Naruto Next Generations متعلق به ناروتو نیست بلکه درباره نینجاهای جوانی از نسل جدید است که آمده اند تا جا پای او بگذارند و اتفاقاً سر دسته آنها پسر ناورتو، یعنی بروتو است...",
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/boruto.jpg",
    downloadLink:
      "https://fh.bia2anime.site/Series/Anime/00/Boruto.Naruto.Next.Generations/Boruto.Naruto.Next.Generations.01.720.bitdownload.ir.mkv",
  },
  {
    postName: "ip man",
    score: "7.1",
    genreList: ["اکشن", "درام", "تاریخی"],
    country: "چین",
    startYear: "2018",
    endYear: "",
    isOnGoing: false,
    language: "چینی",
    duration: "92",
    summery: "خلاصه ی زندگی قهرمان هنر های رزمی چینی ایپ من را روایت میکند",
    seasonNumber: "",
    episodeNumber: "",
    pictureLink: "resources/images/moviesPosters/ip man.jpg",
    downloadLink:
      "https://fh.bia2anime.site/Series/Anime/00/Boruto.Naruto.Next.Generations/Boruto.Naruto.Next.Generations.01.720.bitdownload.ir.mkv",
  },
  {
    postName: "Rick and Morty",
    score: "9.2",
    genreList: ["اکشن", "ماجراجویی", "فانتزی", "کمدی"],
    country: "آمریکا",
    startYear: "2009",
    endYear: "2022",
    isOnGoing: true,
    language: "انگلیسی",
    duration: "23",
    summery:
      "ریک سانچز، دانشمند نابغهٔ الکلی است که به‌تازگی در خانهٔ دخترش، بِث که یک دامپزشک و جراح قلب اسب است، زندگی می‌کند. او اوقاتش را حول کار بر روی پروژه‌های محرمانهٔ علمی بی‌شمارش و ماجراجویی‌های خطرناک در کهکشان‌ها به‌اتفاق نوهٔ نوجوانش، مورتی (و گه‌گاهی همراه با سامر، نوهٔ بزرگترش) می‌گذراند. درآمیختن این اتفاقات با کشمکش‌های خانوادگی، باعث پریشانی و اضطراب بیشتر مورتی در مدرسه و خانه شده‌است.",
    seasonNumber: "6",
    episodeNumber: "2",
    pictureLink: "resources/images/serialsPosters/Rick and Morty.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Overlord/Overlord.IV/Overlord.IV.01.720p.Bia2Anime.mkv",
  },
  {
    postName: "RWBY",
    score: "6.6",
    genreList: [
      "اکشن",
      "ماجراجویی",
      "خوناشام",
      "فانتزی",
      "مدرسه ای",
      "جادویی",
      "کمدی",
    ],
    country: "ژاپن",
    startYear: "2021",
    endYear: "2022",
    isOnGoing: false,
    language: "ژاپنی",
    duration: "23",
    summery:
      "پس از زنده ماندن از حمله قبیله رقیب کوگا، ایتوکی ساکورابا، یک پسر معمولی، متوجه می شود که نوزدهمین وارث نینجای ایگا است. ایتوکی یاد می گیرد که یک نینجا قبیله ایگا شود و به جنگ بین قبیله ایگا و کوگا می پیوندد.",
    seasonNumber: "1",
    episodeNumber: "13",
    pictureLink: "resources/images/serialsPosters/Rwby.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Overlord/Overlord.IV/Overlord.IV.01.720p.Bia2Anime.mkv",
  },
  {
    postName: "Killers",
    score: "7.5",
    genreList: ["اکشن", "درام", "ماجراجویی", "مدرسه ای"],
    country: "ژاپن",
    startYear: "2018",
    endYear: "",
    isOnGoing: true,
    language: "ژاپنی",
    duration: "24",
    summery:
      '"آشیتو آئوی" استعداد فوق العاده ای در ورزش فوتبال دارد، اما سعی می کند آن را پنهان کند. امیدهای او برای ورود به دبیرستان با یک باشگاه فوتبال خوب زمانی از بین می رود که در جریان یک مسابقه حساس برای تیمش حادثه ای ایجاد می کند که منجر به باخت و حذف آنها از مسابقات می شود.با این حال، او نظر شخص مهمی را جلب می کندک',
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/killers.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Ao Ashi",
    score: "7.3",
    genreList: ["درام", "ماجراجویی", "ورزشی", "کمدی"],
    country: "",
    startYear: "2015",
    endYear: "2019",
    isOnGoing: false,
    language: "ژاپنی",
    duration: "24",
    summery:
      '"آشیتو آئوی" استعداد فوق العاده ای در ورزش فوتبال دارد، اما سعی می کند آن را پنهان کند. امیدهای او برای ورود به دبیرستان با یک باشگاه فوتبال خوب زمانی از بین می رود که در جریان یک مسابقه حساس برای تیمش حادثه ای ایجاد می کند که منجر به باخت و حذف آنها از مسابقات می شود.با این حال، او نظر شخص مهمی را جلب می کندکه.',
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/Ao Ashi.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Advanced Fight",
    score: "7.2",
    genreList: ["اکشن", "درام", "ماجراجویی", "شونن", "جادویی", "کمدی"],
    country: "ژاپن",
    startYear: "2015",
    endYear: "2019",
    isOnGoing: false,
    language: "ژاپنی",
    duration: "24",
    summery:
      '"آشیتو آئوی" استعداد فوق العاده ای در ورزش فوتبال دارد، اما سعی می کند آن را پنهان کند. امیدهای او برای ورود به دبیرستان با یک باشگاه فوتبال خوب زمانی از بین می رود که در جریان یک مسابقه حساس برای تیمش حادثه ای ایجاد می کند که منجر به باخت و حذف آنها از مسابقات می شود.با این حال، او نظر شخص مهمی را جلب می کندکه.',
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/advanced fight.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "happy friends",
    score: "7.2",
    genreList: ["درام", "ماجراجویی", "رومانتیک", "مدرسه ای", "جادویی", "کمدی"],
    country: "ژاپن",
    startYear: "2015",
    endYear: "2019",
    isOnGoing: false,
    language: "ژاپنی",
    duration: "24",
    summery:
      '"آشیتو آئوی" استعداد فوق العاده ای در ورزش فوتبال دارد، اما سعی می کند آن را پنهان کند. امیدهای او برای ورود به دبیرستان با یک باشگاه فوتبال خوب زمانی از بین می رود که در جریان یک مسابقه حساس برای تیمش حادثه ای ایجاد می کند که منجر به باخت و حذف آنها از مسابقات می شود.با این حال، او نظر شخص مهمی را جلب می کندکه.',
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/happy friends.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Spy x Family",
    score: "9",
    genreList: [
      "اکشن",
      "درام",
      "ماجراجویی",
      "رومانتیک",
      "مدرسه ای",
      "جادویی",
      "کمدی",
    ],
    country: "ژاپن",
    startYear: "2015",
    endYear: "",
    isOnGoing: true,
    language: "ژاپنی",
    duration: "24",
    summery:
      'ژاپن بارها و بارها جام جهانی را از دست می دهد. پس از اینکه ایساگی یویچی، مهاجم یک تیم دبیرستانی در آخرین بازی در مرحله مقدماتی ملی پوشان حذف شد، به برنامه ای به نام "قفل آبی" دعوت شد، مربی آنها ...',
    seasonNumber: "1",
    episodeNumber: "1",
    pictureLink: "resources/images/serialsPosters/spy x family.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "the Dog",
    score: "9",
    genreList: [
      "اکشن",
      "درام",
      "ماجراجویی",
      "رومانتیک",
      "مدرسه ای",
      "جادویی",
      "کمدی",
    ],
    country: "آمریکا",
    startYear: "2015",
    endYear: "2017",
    isOnGoing: false,
    language: "انگلیسی",
    duration: "22",
    summery:
      "در دورانی که تعداد زیادی از شرکت‌ها وارد فضا شده‌اند و یک سیستم اقتصادی عظیم را ساخته‌اند، Suletta Mercury از سیاره دوردست تیر، به مدرسه فناوری Asticassia که توسط گروه Beneritt اداره می‌شود، منتقل می‌شود.",
    seasonNumber: "1",
    episodeNumber: "2",
    pictureLink: "resources/images/serialsPosters/doggy dog.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Ambulance",
    score: "6.2",
    genreList: [
      "اکشن",
      "درام",
      "ماجراجویی",
      "رومانتیک",
      "مدرسه ای",
      "جادویی",
      "کمدی",
    ],
    country: "آمریکا",
    startYear: "2015",
    endYear: "",
    isOnGoing: false,
    language: "انگلیسی",
    duration: "95",
    summery:
      "یک شرور محکوم به فنا در یک بازی دوستیابی به سرنوشت و نقش خود پی می برد و سعی می کند با برقراری ارتباط عاشقانه با شرور دیگر بازی از نابودی خود جلوگیری کند.",
    seasonNumber: "",
    episodeNumber: "",
    pictureLink: "resources/images/moviesPosters/Ambulance.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Italian Studies",
    score: "3.4",
    genreList: ["درام", "ماجراجویی", "رومانتیک", "موسیقی"],
    country: "آمریکا",
    startYear: "2017",
    endYear: "",
    isOnGoing: false,
    language: "انگلیسی",
    duration: "102",
    summery:
      "یک شرور محکوم به فنا در یک بازی دوستیابی به سرنوشت و نقش خود پی می برد و سعی می کند با برقراری ارتباط عاشقانه با شرور دیگر بازی از نابودی خود جلوگیری کند.",
    seasonNumber: "",
    episodeNumber: "",
    pictureLink: "resources/images/moviesPosters/Italian Studies.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "kung fu man",
    score: "6.3",
    genreList: ["اکشن", "درام", "ماجراجویی", "تاریخی", "کمدی"],
    country: "چین",
    startYear: "2016",
    endYear: "",
    isOnGoing: false,
    language: "چینی",
    duration: "100",
    summery:
      "یک شرور محکوم به فنا در یک بازی دوستیابی به سرنوشت و نقش خود پی می برد و سعی می کند با برقراری ارتباط عاشقانه با شرور دیگر بازی از نابودی خود جلوگیری کند.",
    seasonNumber: "",
    episodeNumber: "",
    pictureLink: "resources/images/moviesPosters/kung fu man.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
  {
    postName: "Bleach",
    score: "8.6",
    genreList: [
      "اکشن",
      "درام",
      "ماجراجویی",
      "تاریخی",
      "فانتزی",
      "شونن",
      "جادویی",
      "کمدی",
    ],
    country: "ژاپن",
    startYear: "2004",
    endYear: "",
    isOnGoing: true,
    language: "ژاپنی",
    duration: "24",
    summery:
      "ادامه انیمه بلیچ (2004). نبرد ایچیگو کوروساکی و همراهانش سول ریپر علیه یواچ و ارتش نفرت انگیز کوئینسی را دنبال می کند.",
    seasonNumber: "12",
    episodeNumber: "1",
    pictureLink: "resources/images/moviesPosters/Bleach.jpg",
    downloadLink:
      "https://s1.bia2anime.site/Series/Anime/Kingdom/Season.1/Kingdom.08.720p.Bia2Anime.mkv",
  },
];
